add_newline = false
format = "$directory$git_branch${env_var.STARSHIP_ASYNC_GIT_FILES}${env_var.STARSHIP_ASYNC_GIT_ADDITIONS}${env_var.STARSHIP_ASYNC_GIT_DELETIONS}$cmd_duration$line_break$character"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"

[cmd_duration]
format = "[$duration]($style) "

[directory]
style = "cyan bold"
format = " [$path]($style) "
truncate_to_repo = false

[git_branch]
symbol = " "
format = "on [$symbol$branch]($style) "
style = "fg:#ea9a97 bold" # Rose color for git branch

[env_var.STARSHIP_ASYNC_GIT_FILES]
format = "[ $env_value •](bold white) "

[env_var.STARSHIP_ASYNC_GIT_ADDITIONS]
format = "[+$env_value](bold green) "

[env_var.STARSHIP_ASYNC_GIT_DELETIONS]
format = "[-$env_value](bold red) "
